### ISSUE TITLE
superset notes

### ISSUE THREAD

**Issue by tianhaoz95** [tianhaoz95/pylon#18]
```yml
mysql:
  image: mysql:5.7
  restart: unless-stopped
  ports:
    - "127.0.0.1:3307:3306"
  environment:
    MYSQL_ROOT_PASSWORD: superset
    MYSQL_DATABASE: superset
    MYSQL_USER: superset
    MYSQL_PASSWORD: superset
  volumes:
    - mysql:/var/lib/mysql
```

`mysql://superset:XXXXXXXXXX@mysql:3306/superset`
