### ISSUE TITLE
tensorman notes

### ISSUE THREAD

**Issue by tianhaoz95** [tianhaoz95/pylon#19]
`tensorman` config, `~/.config/tensorman/config.toml`:

```toml
docker_flags = [
    '-p', '9088:9088',
    '-v', '/home/tianhaoz/Infra/tensorman/bin:/tools'
]
tag = 'latest'
variants = ['gpu', 'python3', 'jupyter']
```

script for starting notebook server

```bash
#!/bin/sh

jupyter notebook --ip 0.0.0.0 --port 9088 --no-browser --NotebookApp.token='tianhaoz'
```
