### ISSUE TITLE
code server note

### ISSUE THREAD

**Issue by tianhaoz95** [tianhaoz95/pylon#20]
config file:

```yml
bind-addr: 127.0.0.1:9188
auth: password
password: *****
cert: false
```

https://github.com/cdr/code-server/blob/main/docs/guide.md

https://github.com/cdr/code-server

https://github.com/cdr/code-server/blob/main/docs/FAQ.md
